alter table public.prompts
  add column if not exists contribuidor text;

alter table public.prompts
  add constraint prompts_contribuidor_length
  check (contribuidor is null or char_length(contribuidor) <= 200);

comment on column public.prompts.contribuidor is
  'Public name chosen by the contributor credited for the prompt.';

create table public.prompt_suggestions (
  id bigint generated by default as identity primary key,
  categoria text not null check (char_length(categoria) between 1 and 160),
  subcategoria text not null check (char_length(subcategoria) between 1 and 160),
  ia text not null check (char_length(ia) between 1 and 80),
  nombre text not null check (char_length(nombre) between 1 and 300),
  prompt text not null check (char_length(prompt) between 1 and 50000),
  notas text not null default '' check (char_length(notas) <= 10000),
  premium boolean not null default false,
  contribuidor text not null check (char_length(contribuidor) between 1 and 200),
  suggested_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.prompt_suggestions enable row level security;

revoke all on table public.prompt_suggestions from public, anon, authenticated;
grant select, insert, delete on table public.prompt_suggestions to service_role;
grant usage, select on sequence public.prompt_suggestions_id_seq to service_role;

create or replace function public.extract_prompt_suggestions()
returns setof public.prompt_suggestions
language sql
security invoker
set search_path = ''
as $$
  with extracted as (
    delete from public.prompt_suggestions
    returning *
  )
  select *
  from extracted
  order by created_at, id;
$$;

revoke all on function public.extract_prompt_suggestions() from public, anon, authenticated;
grant execute on function public.extract_prompt_suggestions() to service_role;

comment on function public.extract_prompt_suggestions() is
  'Atomically returns and removes all pending prompt suggestions with service_role privileges.';
